[template]
cargo_generate_version = ">=0.10.0"

[placeholders.framework]
type = "string"
prompt = "Which framework would you like to use?"
choices = ["stm32rs", "embassy"]
default = "embassy"

[placeholders.mcu]
type = "string"
prompt = "Which STM32 MCU are you targeting?"
choices = [
    "stm32f401re"
]
default = "stm32f401re"

[placeholders.sensor]
type = "string"
prompt = "Which sensor you want?"
choices = [
    "no_sensor",
    "lsm6dsv16x"
]
default = "no_sensor"

[conditional.'framework == "stm32rs"']
ignore = [
    "defmt.toml"
]

[conditional.'framework == "no_sensor"']
ignore = [
    "src/who_am_i.rs"
]
